name: Daily Sync Ratings from Render

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 06:00 UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  sync-ratings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Sync ratings from Render into SQLite
      run: python scripts/sync_ratings.py

    - name: Commit updated DB
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add data/sustainability.db
        git commit -m "Sync new ratings into sustainability.db" || echo "No changes to commit"
        git push
